/**
 * General Pokepost configuration.
 * This configuration is compiled to `./pokemon-data.json` at build time.
 */

var FrequencyFactor = {
    VeryCommon: 12,
    Common: 8,
    SemiRare: 6,
    Rare: 4,
    Legendary: 2,
    NearImpossible: 1,
};

var CaptureRate = {
    VeryEasy: 0.9,
    Easy: 0.8,
    Medium: 0.7,
    Hard: 0.6,
    VeryHard: 0.5,
};

module.exports = {

    /**
     * Max age in milliseconds for a post to be considered as "new".
     * Only a new post can be used to generate an encounter.
     * @type {Number}
     */
    postMaxAgeMs: 300000, // 5 * 60 * 1000 = 5 minutes

    /**
     * Probability of encountering a Pokémon at each post
     * (see EncounterGenerator constructor).
     * @type {Number}
     */
    globalEncounterRate: 0.35,

    /**
     * Catchable Pokémon list.
     * @type {object[]} Pokémon list : {
     *     id: Pokémon unique identifier
     *     no: Pokédex number
     *     name: Pokémon name
     *     frequencyFactor: Positive integer
     *         (see EncounterGenerator#setPokemonRepartitionList)
     *     captureRate: Between 0 and 1
     * }
     */
    pokemonList: [
        {
            id: 'bulbizarre',
            no: 1,
            name: 'Bulbizarre',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'herbizarre',
            no: 2,
            name: 'Herbizarre',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'florizarre',
            no: 3,
            name: 'Florizarre',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'salameche',
            no: 4,
            name: 'Salamèche',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'reptincel',
            no: 5,
            name: 'Reptincel',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'dracaufeu',
            no: 6,
            name: 'Dracaufeu',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'carapuce',
            no: 7,
            name: 'Carapuce',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'carabaffe',
            no: 8,
            name: 'Carabaffe',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'tortank',
            no: 9,
            name: 'Tortank',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'chenipan',
            no: 10,
            name: 'Chenipan',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'chrysacier',
            no: 11,
            name: 'Chrysacier',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'papilusion',
            no: 12,
            name: 'Papilusion',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'aspicot',
            no: 13,
            name: 'Aspicot',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'coconfort',
            no: 14,
            name: 'Coconfort',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'dardargnan',
            no: 15,
            name: 'Dardargnan',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'roucool',
            no: 16,
            name: 'Roucool',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'roucoups',
            no: 17,
            name: 'Roucoups',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'roucarnage',
            no: 18,
            name: 'Roucarnage',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'rattata',
            no: 19,
            name: 'Rattata',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'rattatac',
            no: 20,
            name: 'Rattatac',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'piafabec',
            no: 21,
            name: 'Piafabec',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'rapasdepic',
            no: 22,
            name: 'Rapasdepic',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'abo',
            no: 23,
            name: 'Abo',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'arbok',
            no: 24,
            name: 'Arbok',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'pikachu',
            no: 25,
            name: 'Pikachu',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'raichu',
            no: 26,
            name: 'Raichu',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'sabelette',
            no: 27,
            name: 'Sabelette',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'sablaireau',
            no: 28,
            name: 'Sablaireau',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'nidoran_femelle',
            no: 29,
            name: 'Nidoran♀',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'nidorina',
            no: 30,
            name: 'Nidorina',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'nidoqueen',
            no: 31,
            name: 'Nidoqueen',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'nidoran_male',
            no: 32,
            name: 'Nidoran♂',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'nidorino',
            no: 33,
            name: 'Nidorino',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'nidoking',
            no: 34,
            name: 'Nidoking',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'melofee',
            no: 35,
            name: 'Mélofée',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'melodelfe',
            no: 36,
            name: 'Mélodelfe',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'goupix',
            no: 37,
            name: 'Goupix',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'feunard',
            no: 38,
            name: 'Feunard',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'rondoudou',
            no: 39,
            name: 'Rondoudou',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'grodoudou',
            no: 40,
            name: 'Grodoudou',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'nosferapti',
            no: 41,
            name: 'Nosferapti',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'nosferalto',
            no: 42,
            name: 'Nosferalto',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'mystherbe',
            no: 43,
            name: 'Mystherbe',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'ortide',
            no: 44,
            name: 'Ortide',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'rafflesia',
            no: 45,
            name: 'Rafflésia',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'paras',
            no: 46,
            name: 'Paras',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'parasect',
            no: 47,
            name: 'Parasect',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'mimitoss',
            no: 48,
            name: 'Mimitoss',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'aeromite',
            no: 49,
            name: 'Aéromite',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'taupiqueur',
            no: 50,
            name: 'Taupiqueur',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'triopikeur',
            no: 51,
            name: 'Triopikeur',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'miaouss',
            no: 52,
            name: 'Miaouss',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'persian',
            no: 53,
            name: 'Persian',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'psykokwak',
            no: 54,
            name: 'Psykokwak',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'akwakwak',
            no: 55,
            name: 'Akwakwak',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'ferosinge',
            no: 56,
            name: 'Férosinge',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'colossinge',
            no: 57,
            name: 'Colossinge',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'caninos',
            no: 58,
            name: 'Caninos',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'arcanin',
            no: 59,
            name: 'Arcanin',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'ptitard',
            no: 60,
            name: 'Ptitard',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'tetarte',
            no: 61,
            name: 'Têtarte',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'tartard',
            no: 62,
            name: 'Tartard',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'abra',
            no: 63,
            name: 'Abra',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryHard,
        },
        {
            id: 'kadabra',
            no: 64,
            name: 'Kadabra',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'alakazam',
            no: 65,
            name: 'Alakazam',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'machoc',
            no: 66,
            name: 'Machoc',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'machopeur',
            no: 67,
            name: 'Machopeur',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'mackogneur',
            no: 68,
            name: 'Mackogneur',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'chetiflor',
            no: 69,
            name: 'Chétiflor',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'boustiflor',
            no: 70,
            name: 'Boustiflor',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'empiflor',
            no: 71,
            name: 'Empiflor',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'tentacool',
            no: 72,
            name: 'Tentacool',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'tentacruel',
            no: 73,
            name: 'Tentacruel',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'racaillou',
            no: 74,
            name: 'Racaillou',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'gravalanch',
            no: 75,
            name: 'Gravalanch',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'grolem',
            no: 76,
            name: 'Grolem',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'ponyta',
            no: 77,
            name: 'Ponyta',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'galopa',
            no: 78,
            name: 'Galopa',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'ramoloss',
            no: 79,
            name: 'Ramoloss',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'flagadoss',
            no: 80,
            name: 'Flagadoss',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'magneti',
            no: 81,
            name: 'Magnéti',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'magneton',
            no: 82,
            name: 'Magnéton',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'canarticho',
            no: 83,
            name: 'Canarticho',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'doduo',
            no: 84,
            name: 'Doduo',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'dodrio',
            no: 85,
            name: 'Dodrio',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'otaria',
            no: 86,
            name: 'Otaria',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'lamantine',
            no: 87,
            name: 'Lamantine',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'tadmorv',
            no: 88,
            name: 'Tadmorv',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'grotadmorv',
            no: 89,
            name: 'Grotadmorv',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'kokiyas',
            no: 90,
            name: 'Kokiyas',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'crustabri',
            no: 91,
            name: 'Crustabri',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'fantominus',
            no: 92,
            name: 'Fantominus',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'spectrum',
            no: 93,
            name: 'Spectrum',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'ectoplasma',
            no: 94,
            name: 'Ectoplasma',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'onix',
            no: 95,
            name: 'Onix',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'soporifik',
            no: 96,
            name: 'Soporifik',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'hypnomade',
            no: 97,
            name: 'Hypnomade',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'krabby',
            no: 98,
            name: 'Krabby',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'krabboss',
            no: 99,
            name: 'Krabboss',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'voltorbe',
            no: 100,
            name: 'Voltorbe',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'electrode',
            no: 101,
            name: 'Électrode',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'noeunoeuf',
            no: 102,
            name: 'Nœunœuf',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'noadkoko',
            no: 103,
            name: 'Noadkoko',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'osselait',
            no: 104,
            name: 'Osselait',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'ossatueur',
            no: 105,
            name: 'Ossatueur',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'kicklee',
            no: 106,
            name: 'Kicklee',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'tygnon',
            no: 107,
            name: 'Tygnon',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'excelangue',
            no: 108,
            name: 'Excelangue',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'smogo',
            no: 109,
            name: 'Smogo',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'smogogo',
            no: 110,
            name: 'Smogogo',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'rhinocorne',
            no: 111,
            name: 'Rhinocorne',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'rhinoferos',
            no: 112,
            name: 'Rhinoféros',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'leveinard',
            no: 113,
            name: 'Leveinard',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'saquedeneu',
            no: 114,
            name: 'Saquedeneu',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'kangourex',
            no: 115,
            name: 'Kangourex',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'hypotrempe',
            no: 116,
            name: 'Hypotrempe',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'hypocean',
            no: 117,
            name: 'Hypocéan',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'poissirene',
            no: 118,
            name: 'Poissirène',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'poissoroy',
            no: 119,
            name: 'Poissoroy',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'stari',
            no: 120,
            name: 'Stari',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Easy,
        },
        {
            id: 'staross',
            no: 121,
            name: 'Staross',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'm_mime',
            no: 122,
            name: 'M. Mime',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'insecateur',
            no: 123,
            name: 'Insécateur',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'lippoutou',
            no: 124,
            name: 'Lippoutou',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'elektek',
            no: 125,
            name: 'Élektek',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'magmar',
            no: 126,
            name: 'Magmar',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'scarabrute',
            no: 127,
            name: 'Scarabrute',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'tauros',
            no: 128,
            name: 'Tauros',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'magicarpe',
            no: 129,
            name: 'Magicarpe',
            frequencyFactor: FrequencyFactor.VeryCommon,
            captureRate: CaptureRate.VeryEasy,
        },
        {
            id: 'leviator',
            no: 130,
            name: 'Léviator',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'lokhlass',
            no: 131,
            name: 'Lokhlass',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'metamorph',
            no: 132,
            name: 'Métamorph',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'evoli',
            no: 133,
            name: 'Évoli',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'aquali',
            no: 134,
            name: 'Aquali',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'voltali',
            no: 135,
            name: 'Voltali',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'pyroli',
            no: 136,
            name: 'Pyroli',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'porygon',
            no: 137,
            name: 'Porygon',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'amonita',
            no: 138,
            name: 'Amonita',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'amonistar',
            no: 139,
            name: 'Amonistar',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'kabuto',
            no: 140,
            name: 'Kabuto',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'kabutops',
            no: 141,
            name: 'Kabutops',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'ptera',
            no: 142,
            name: 'Ptéra',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'ronflex',
            no: 143,
            name: 'Ronflex',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.VeryHard,
        },
        {
            id: 'artikodin',
            no: 144,
            name: 'Artikodin',
            frequencyFactor: FrequencyFactor.Legendary,
            captureRate: CaptureRate.VeryHard,
        },
        {
            id: 'electhor',
            no: 145,
            name: 'Électhor',
            frequencyFactor: FrequencyFactor.Legendary,
            captureRate: CaptureRate.VeryHard,
        },
        {
            id: 'sulfura',
            no: 146,
            name: 'Sulfura',
            frequencyFactor: FrequencyFactor.Legendary,
            captureRate: CaptureRate.VeryHard,
        },
        {
            id: 'minidraco',
            no: 147,
            name: 'Minidraco',
            frequencyFactor: FrequencyFactor.Common,
            captureRate: CaptureRate.Medium,
        },
        {
            id: 'draco',
            no: 148,
            name: 'Draco',
            frequencyFactor: FrequencyFactor.SemiRare,
            captureRate: CaptureRate.Hard,
        },
        {
            id: 'dracolosse',
            no: 149,
            name: 'Dracolosse',
            frequencyFactor: FrequencyFactor.Rare,
            captureRate: CaptureRate.VeryHard,
        },
        {
            id: 'mewtwo',
            no: 150,
            name: 'Mewtwo',
            frequencyFactor: FrequencyFactor.NearImpossible,
            captureRate: CaptureRate.VeryHard,
        },
        {
            id: 'mew',
            no: 151,
            name: 'Mew',
            frequencyFactor: FrequencyFactor.NearImpossible,
            captureRate: CaptureRate.VeryHard,
        },
    ],
};
