#!/bin/bash

# Empêche la faute de frappe "recontre" à la place de "rencontre".

if [ $(git diff --cached --name-only --diff-filter=ACM | xargs grep recontre | wc -l) -gt 0 ]
then
    echo "You're committing a spelling mistake !"
    git diff --cached --name-only --diff-filter=ACM | xargs grep --color -Hn recontre
    exit 1
fi
